# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: ftms docker build
    #needs: unit-test
    runs-on: Docker
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: login-github-registy
        uses: docker/login-action@v1
        with:
          registry: github.aepsc.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: login-artifactory-registry
        uses: docker/login-action@v1
        with:
          registry: docker.rtfx.aepsc.com
          username: ${{ secrets.ARTIFACTORY_DEPLOY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_DEPLOY_PASSWORD }}
      - name: Dockerize App
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: docker.rtfx.aepsc.com/aep-icoe-cp-artifacts/ftms:${{ github.sha }}
